/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Comment = {
  _id: string;
  _type: "comment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  text: string;
  chapter: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "chapter";
  };
};

export type Chapter = {
  _id: string;
  _type: "chapter";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  chapter_title: string;
  slug: Slug;
  chapter_number: number;
  story?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "story";
  };
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Story = {
  _id: string;
  _type: "story";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  keywords?: Array<string>;
  genre: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "genre";
  };
  fandom: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "fandom";
  };
  featured?: boolean;
  completed?: boolean;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  summary?: string;
  pairings?: string;
  notes?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Fandom = {
  _id: string;
  _type: "fandom";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  genre: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "genre";
  };
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  summary?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Genre = {
  _id: string;
  _type: "genre";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Comment | Chapter | Story | SanityImageCrop | SanityImageHotspot | Fandom | Slug | Genre | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: sanity/lib/queries.ts
// Variable: GENRES_WITH_STORIES_QUERY
// Query: *[_type == "genre"]{    _id,    slug,    title,    "stories": *[      _type == "story" &&      genre._ref == ^._id    ][0...3]{      _id,      title,      slug,      completed,      summary,      image,      "genre": genre->{        title,        slug      },      "fandom": fandom->{        title,        slug      }    }  }
export type GENRES_WITH_STORIES_QUERYResult = Array<{
  _id: string;
  slug: Slug;
  title: string;
  stories: Array<{
    _id: string;
    title: string;
    slug: Slug;
    completed: boolean | null;
    summary: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    genre: {
      title: string;
      slug: Slug;
    };
    fandom: {
      title: string;
      slug: Slug;
    };
  }>;
}>;
// Variable: FANDOMS_WITH_STORIES_QUERY
// Query: *[_type == "fandom" && genre->slug.current == $genreSlug]{    _id,    slug,    title,    "stories": *[      _type == "story" &&      fandom._ref == ^._id    ][0...3]{      _id,      title,      slug,      completed,      summary,      image,      "genre": genre->{        title,        slug      },      "fandom": fandom->{        title,        slug      }    }  }
export type FANDOMS_WITH_STORIES_QUERYResult = Array<{
  _id: string;
  slug: Slug;
  title: string;
  stories: Array<{
    _id: string;
    title: string;
    slug: Slug;
    completed: boolean | null;
    summary: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    genre: {
      title: string;
      slug: Slug;
    };
    fandom: {
      title: string;
      slug: Slug;
    };
  }>;
}>;
// Variable: STORIES_FOR_FANDOM_QUERY
// Query: *[_type == "story" && fandom->slug.current == $fandomSlug]{    _id,    title,    slug,    completed,    summary,    image,    "genre": genre->{      title,      slug    },    "fandom": fandom->{      title,      slug,      image,      summary    }  }
export type STORIES_FOR_FANDOM_QUERYResult = Array<{
  _id: string;
  title: string;
  slug: Slug;
  completed: boolean | null;
  summary: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  genre: {
    title: string;
    slug: Slug;
  };
  fandom: {
    title: string;
    slug: Slug;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    summary: string | null;
  };
}>;
// Variable: FEATURED_STORIES_QUERY
// Query: *[_type == "story" && featured == true]{    _id,    title,    slug,    completed,    summary,    image,    "genre": genre->{      title,      slug    },    "fandom": fandom->{      title,      slug    }  }
export type FEATURED_STORIES_QUERYResult = Array<{
  _id: string;
  title: string;
  slug: Slug;
  completed: boolean | null;
  summary: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  genre: {
    title: string;
    slug: Slug;
  };
  fandom: {
    title: string;
    slug: Slug;
  };
}>;
// Variable: STORY_QUERY
// Query: *[_type == "story" && slug.current == $storySlug][0]{    _id,    title,    slug,    completed,    summary,    image,    "genre": genre->{      title,      slug    },    "fandom": fandom->{      title,      slug    }  }
export type STORY_QUERYResult = {
  _id: string;
  title: string;
  slug: Slug;
  completed: boolean | null;
  summary: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  genre: {
    title: string;
    slug: Slug;
  };
  fandom: {
    title: string;
    slug: Slug;
  };
} | null;
// Variable: STORY_PAGE_QUERY
// Query: *[_type == "story" && slug.current == $storySlug][0]{    _id,    title,    slug,    completed,    "fandom": fandom->{      title,      slug    },    summary,    pairings,    notes,    image,    "firstChapter": *[      _type == "chapter" &&      story._ref == ^._id &&      chapter_number == 0    ][0]{      chapter_title,      slug,      chapter_number,    },    "chapters": *[      _type == "chapter" &&      story._ref == ^._id] |       order(chapter_number asc      ){        chapter_title,        slug,        chapter_number    }  }
export type STORY_PAGE_QUERYResult = {
  _id: string;
  title: string;
  slug: Slug;
  completed: boolean | null;
  fandom: {
    title: string;
    slug: Slug;
  };
  summary: string | null;
  pairings: string | null;
  notes: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  firstChapter: {
    chapter_title: string;
    slug: Slug;
    chapter_number: number;
  } | null;
  chapters: Array<{
    chapter_title: string;
    slug: Slug;
    chapter_number: number;
  }>;
} | null;
// Variable: CHAPTER_PAGE_QUERY
// Query: *[_type == "chapter" &&    story->slug.current == $storySlug &&    slug.current == $chapterSlug  ][0]{    _id,    chapter_title,    slug,    chapter_number,    "story": story->{      title,      slug,      completed    },    body,    "prev": *[      _type == "chapter" &&      story._ref == ^.story._ref &&      chapter_number == ^.chapter_number - 1    ][0]{ slug },    "next": *[      _type == "chapter" &&      story._ref == ^.story._ref &&      chapter_number == ^.chapter_number + 1    ][0]{ slug },    "comments": *[      _type == "comment" &&      chapter._ref == ^._id    ] | order(_createdAt desc){      _id,      name,      text,      _createdAt    }  }
export type CHAPTER_PAGE_QUERYResult = {
  _id: string;
  chapter_title: string;
  slug: Slug;
  chapter_number: number;
  story: {
    title: string;
    slug: Slug;
    completed: boolean | null;
  } | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  prev: {
    slug: Slug;
  } | null;
  next: {
    slug: Slug;
  } | null;
  comments: Array<{
    _id: string;
    name: string;
    text: string;
    _createdAt: string;
  }>;
} | null;
// Variable: NAVIGATION_QUERY
// Query: {  "genres": *[_type == "genre"] | order(title asc){    _id,    title,    slug,    "fandoms": *[      _type == "fandom" &&      genre._ref == ^._id    ] | order(title asc){      _id,      title,      slug,      "stories": *[        _type == "story" &&        fandom._ref == ^._id      ] | order(title asc){        _id,        title,        slug      }    }  }}
export type NAVIGATION_QUERYResult = {
  genres: Array<{
    _id: string;
    title: string;
    slug: Slug;
    fandoms: Array<{
      _id: string;
      title: string;
      slug: Slug;
      stories: Array<{
        _id: string;
        title: string;
        slug: Slug;
      }>;
    }>;
  }>;
};
// Variable: SEARCH_QUERY
// Query: *[_type == "story"      && (      title match $queryString + '*'       || pairings match $queryString + '*'       || keywords match $queryString + '*'       || genre->title match $queryString + '*'      || fandom->title match $queryString + '*')]       | order(publishedAt desc){        _id,        title,        slug,        completed,        summary,        image,        "genre": genre->{          title,          slug        },        "fandom": fandom->{          title,          slug        }            }
export type SEARCH_QUERYResult = Array<{
  _id: string;
  title: string;
  slug: Slug;
  completed: boolean | null;
  summary: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  genre: {
    title: string;
    slug: Slug;
  };
  fandom: {
    title: string;
    slug: Slug;
  };
}>;
// Variable: GENRE_PARAMS_QUERY
// Query: *[_type == "genre"]{    "genre": slug.current  }
export type GENRE_PARAMS_QUERYResult = Array<{
  genre: string;
}>;
// Variable: FANDOM_PARAMS_QUERY
// Query: *[_type == "fandom"]{    "genre": genre->slug.current,    "fandom": slug.current  }
export type FANDOM_PARAMS_QUERYResult = Array<{
  genre: string;
  fandom: string;
}>;
// Variable: STORY_PARAMS_QUERY
// Query: *[_type == "story"]{    "genre": genre->slug.current,    "fandom": fandom->slug.current,    "story": slug.current  }
export type STORY_PARAMS_QUERYResult = Array<{
  genre: string;
  fandom: string;
  story: string;
}>;
// Variable: CHAPTER_PARAMS_QUERY
// Query: *[_type == "chapter"]{    "genre": story->genre->slug.current,    "fandom": story->fandom->slug.current,    "story": story->slug.current,    "chapter": slug.current  }
export type CHAPTER_PARAMS_QUERYResult = Array<{
  genre: string | null;
  fandom: string | null;
  story: string | null;
  chapter: string;
}>;
// Variable: ALL_ROUTES_QUERY
// Query: {  "genres": *[_type == "genre"] | order(title asc){    _id,    _updatedAt,    "genre": slug.current  },  "fandoms": *[_type == "fandom"] | order(title asc){    _id,    _updatedAt,    "genre": genre->slug.current,    "fandom": slug.current  },  "stories": *[_type == "story"] | order(title asc){    _id,    _updatedAt,    "genre": genre->slug.current,    "fandom": fandom->slug.current,    "story": slug.current  },  "chapters": *[_type == "chapter"] | order(chapter_number asc){    _id,    _updatedAt,    "genre": story->genre->slug.current,    "fandom": story->fandom->slug.current,    "story": story->slug.current,    "chapter": slug.current  }}
export type ALL_ROUTES_QUERYResult = {
  genres: Array<{
    _id: string;
    _updatedAt: string;
    genre: string;
  }>;
  fandoms: Array<{
    _id: string;
    _updatedAt: string;
    genre: string;
    fandom: string;
  }>;
  stories: Array<{
    _id: string;
    _updatedAt: string;
    genre: string;
    fandom: string;
    story: string;
  }>;
  chapters: Array<{
    _id: string;
    _updatedAt: string;
    genre: string | null;
    fandom: string | null;
    story: string | null;
    chapter: string;
  }>;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"genre\"]{\n    _id,\n    slug,\n    title,\n    \"stories\": *[\n      _type == \"story\" &&\n      genre._ref == ^._id\n    ][0...3]{\n      _id,\n      title,\n      slug,\n      completed,\n      summary,\n      image,\n      \"genre\": genre->{\n        title,\n        slug\n      },\n      \"fandom\": fandom->{\n        title,\n        slug\n      }\n    }\n  }\n": GENRES_WITH_STORIES_QUERYResult;
    "\n  *[_type == \"fandom\" && genre->slug.current == $genreSlug]{\n    _id,\n    slug,\n    title,\n    \"stories\": *[\n      _type == \"story\" &&\n      fandom._ref == ^._id\n    ][0...3]{\n      _id,\n      title,\n      slug,\n      completed,\n      summary,\n      image,\n      \"genre\": genre->{\n        title,\n        slug\n      },\n      \"fandom\": fandom->{\n        title,\n        slug\n      }\n    }\n  }\n": FANDOMS_WITH_STORIES_QUERYResult;
    "\n  *[_type == \"story\" && fandom->slug.current == $fandomSlug]{\n    _id,\n    title,\n    slug,\n    completed,\n    summary,\n    image,\n    \"genre\": genre->{\n      title,\n      slug\n    },\n    \"fandom\": fandom->{\n      title,\n      slug,\n      image,\n      summary\n    }\n  }\n": STORIES_FOR_FANDOM_QUERYResult;
    "*[_type == \"story\" && featured == true]{\n    _id,\n    title,\n    slug,\n    completed,\n    summary,\n    image,\n    \"genre\": genre->{\n      title,\n      slug\n    },\n    \"fandom\": fandom->{\n      title,\n      slug\n    }\n  }\n": FEATURED_STORIES_QUERYResult;
    "*[_type == \"story\" && slug.current == $storySlug][0]{\n    _id,\n    title,\n    slug,\n    completed,\n    summary,\n    image,\n    \"genre\": genre->{\n      title,\n      slug\n    },\n    \"fandom\": fandom->{\n      title,\n      slug\n    }\n  }\n": STORY_QUERYResult;
    "\n  *[_type == \"story\" && slug.current == $storySlug][0]{\n    _id,\n    title,\n    slug,\n    completed,\n    \"fandom\": fandom->{\n      title,\n      slug\n    },\n    summary,\n    pairings,\n    notes,\n    image,\n    \"firstChapter\": *[\n      _type == \"chapter\" &&\n      story._ref == ^._id &&\n      chapter_number == 0\n    ][0]{\n      chapter_title,\n      slug,\n      chapter_number,\n    },\n    \"chapters\": *[\n      _type == \"chapter\" &&\n      story._ref == ^._id] | \n      order(chapter_number asc\n      ){\n        chapter_title,\n        slug,\n        chapter_number\n    }\n  }\n": STORY_PAGE_QUERYResult;
    "\n  *[_type == \"chapter\" &&\n    story->slug.current == $storySlug &&\n    slug.current == $chapterSlug\n  ][0]{\n    _id,\n    chapter_title,\n    slug,\n    chapter_number,\n    \"story\": story->{\n      title,\n      slug,\n      completed\n    },\n    body,\n    \"prev\": *[\n      _type == \"chapter\" &&\n      story._ref == ^.story._ref &&\n      chapter_number == ^.chapter_number - 1\n    ][0]{ slug },\n    \"next\": *[\n      _type == \"chapter\" &&\n      story._ref == ^.story._ref &&\n      chapter_number == ^.chapter_number + 1\n    ][0]{ slug },\n    \"comments\": *[\n      _type == \"comment\" &&\n      chapter._ref == ^._id\n    ] | order(_createdAt desc){\n      _id,\n      name,\n      text,\n      _createdAt\n    }\n  }\n": CHAPTER_PAGE_QUERYResult;
    "\n{\n  \"genres\": *[_type == \"genre\"] | order(title asc){\n    _id,\n    title,\n    slug,\n    \"fandoms\": *[\n      _type == \"fandom\" &&\n      genre._ref == ^._id\n    ] | order(title asc){\n      _id,\n      title,\n      slug,\n      \"stories\": *[\n        _type == \"story\" &&\n        fandom._ref == ^._id\n      ] | order(title asc){\n        _id,\n        title,\n        slug\n      }\n    }\n  }\n}\n": NAVIGATION_QUERYResult;
    "\n  *[_type == \"story\"\n      && (\n      title match $queryString + '*' \n      || pairings match $queryString + '*' \n      || keywords match $queryString + '*' \n      || genre->title match $queryString + '*'\n      || fandom->title match $queryString + '*')] \n      | order(publishedAt desc){\n        _id,\n        title,\n        slug,\n        completed,\n        summary,\n        image,\n        \"genre\": genre->{\n          title,\n          slug\n        },\n        \"fandom\": fandom->{\n          title,\n          slug\n        }      \n      }\n": SEARCH_QUERYResult;
    "\n  *[_type == \"genre\"]{\n    \"genre\": slug.current\n  }\n": GENRE_PARAMS_QUERYResult;
    "\n  *[_type == \"fandom\"]{\n    \"genre\": genre->slug.current,\n    \"fandom\": slug.current\n  }\n": FANDOM_PARAMS_QUERYResult;
    "\n  *[_type == \"story\"]{\n    \"genre\": genre->slug.current,\n    \"fandom\": fandom->slug.current,\n    \"story\": slug.current\n  }\n": STORY_PARAMS_QUERYResult;
    "\n  *[_type == \"chapter\"]{\n    \"genre\": story->genre->slug.current,\n    \"fandom\": story->fandom->slug.current,\n    \"story\": story->slug.current,\n    \"chapter\": slug.current\n  }\n": CHAPTER_PARAMS_QUERYResult;
    "\n{\n  \"genres\": *[_type == \"genre\"] | order(title asc){\n    _id,\n    _updatedAt,\n    \"genre\": slug.current\n  },\n  \"fandoms\": *[_type == \"fandom\"] | order(title asc){\n    _id,\n    _updatedAt,\n    \"genre\": genre->slug.current,\n    \"fandom\": slug.current\n  },\n  \"stories\": *[_type == \"story\"] | order(title asc){\n    _id,\n    _updatedAt,\n    \"genre\": genre->slug.current,\n    \"fandom\": fandom->slug.current,\n    \"story\": slug.current\n  },\n  \"chapters\": *[_type == \"chapter\"] | order(chapter_number asc){\n    _id,\n    _updatedAt,\n    \"genre\": story->genre->slug.current,\n    \"fandom\": story->fandom->slug.current,\n    \"story\": story->slug.current,\n    \"chapter\": slug.current\n  }\n}\n": ALL_ROUTES_QUERYResult;
  }
}
